### ISSUE TITLE
请问是否支援繁体?

### ISSUE THREAD

**Issue by tents89** [dwing4g/openmw#2]
你好
最近看到新的汉化想试试，但繁体系统用户似乎只会显示???
OpenMW使用gbk无法使用，也尝试了utf8或是修改字体，但是中文仍然无法显示
请问是否有办法支援繁体字?

**Comment by dwing4g** [comment]
运行"reset_cfg"重置配置无法解决吗?

**Comment by tents89** [comment]
> 运行"reset_cfg"重置配置无法解决吗?

没事了,现在可以正常显示
谢谢
